import type { IdiomContent } from "./types";

/**
 * Snippet 1 content: 15 Lower Primary (ages 7-9) idioms, researched and
 * cross-checked against real Chinese reference sources (zdic.net, Baidu
 * Baike, multiple 成语词典 aggregators) rather than generated from
 * memory — see DECISIONS.md's 2026-08-06 entries for the full research
 * summary and rejected-candidates list. All 15 approved as-is on review,
 * including the two editorial calls flagged for explicit sign-off
 * (拔苗助长's colloquial form, and extending 相亲相爱 to family love).
 */
export const idioms: IdiomContent[] = [
  // --- Focus & Perseverance ---
  {
    id: "yi-xin-yi-yi",
    hanzi: "一心一意",
    pinyin: "yī xīn yī yì",
    literalMeaning: "一 (one) 心 (heart) 一 (one) 意 (mind) — one heart, one mind.",
    meaning: "To focus completely on one thing, without letting your attention wander to other things.",
    meaningZh: {
      hanzi: "做事的时候只专心做这一件事，不去想别的事情。",
      pinyin: "Zuò shì de shíhou zhǐ zhuānxīn zuò zhè yí jiàn shì, bú qù xiǎng bié de shìqing.",
      charPinyin: ["zuò", "shì", "de", "shí", "hou", "zhǐ", "zhuān", "xīn", "zuò", "zhè", "yí", "jiàn", "shì", "", "bú", "qù", "xiǎng", "bié", "de", "shì", "qing", ""],
    },
    dailyLifeScenario:
      "You're doing your spelling homework at the kitchen table, but the TV is on and your toys are nearby. If you put everything else aside and give your homework your full attention until it's done, you are being 一心一意.",
    exampleSentence: {
      hanzi: "小明做作业的时候一心一意，不看电视也不玩玩具。",
      pinyin: "Xiǎomíng zuò zuòyè de shíhou yīxīn-yíyì, bú kàn diànshì yě bù wán wánjù.",
      english: "When Xiaoming does his homework, he focuses wholeheartedly — no TV, no toys.",
      charPinyin: ["xiǎo", "míng", "zuò", "zuò", "yè", "de", "shí", "hou", "yī", "xīn", "yí", "yì", "", "bú", "kàn", "diàn", "shì", "yě", "bù", "wán", "wán", "jù", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes:
      "Meaning confirmed via zdic.net and multiple 成语词典 aggregators (origin: Chen Shou's Sanguozhi, 3rd century). Appears on a Malaysian primary school's published idiom list and Singapore PSLE-Chinese-prep compilations.",
  },
  {
    id: "you-shi-you-zhong",
    hanzi: "有始有终",
    pinyin: "yǒu shǐ yǒu zhōng",
    literalMeaning: "有 (have) 始 (a beginning) 有 (have) 终 (an end) — to have both a start and a finish.",
    meaning: "To carry a task all the way through to completion instead of stopping partway.",
    meaningZh: {
      hanzi: "开始做一件事以后，一定要好好地做到完成，不能半路停下来。",
      pinyin: "Kāishǐ zuò yí jiàn shì yǐhòu, yídìng yào hǎohāo de zuò dào wánchéng, bù néng bànlù tíng xiàlái.",
      charPinyin: ["kāi", "shǐ", "zuò", "yí", "jiàn", "shì", "yǐ", "hòu", "", "yí", "dìng", "yào", "hǎo", "hāo", "de", "zuò", "dào", "wán", "chéng", "", "bù", "néng", "bàn", "lù", "tíng", "xià", "lái", ""],
    },
    dailyLifeScenario:
      "You signed up for a school swimming course. After two lessons it feels hard and you want to quit — but you decide to keep going until you finish the whole course. That's 有始有终.",
    exampleSentence: {
      hanzi: "他参加读书计划，从第一页读到最后一页，真是有始有终。",
      pinyin: "Tā cānjiā dúshū jìhuà, cóng dì-yī yè dú dào zuìhòu yī yè, zhēnshi yǒushǐ-yǒuzhōng.",
      english: "He joined a reading program and read from the very first page to the very last — truly seeing it through from start to finish.",
      charPinyin: ["tā", "cān", "jiā", "dú", "shū", "jì", "huà", "", "cóng", "dì", "yī", "yè", "dú", "dào", "zuì", "hòu", "yī", "yè", "", "zhēn", "shi", "yǒu", "shǐ", "yǒu", "zhōng", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning/origin (Analects, 论语·子张) confirmed via zdic.net and Baidu Baike.",
  },
  {
    id: "ban-tu-er-fei",
    hanzi: "半途而废",
    pinyin: "bàn tú ér fèi",
    literalMeaning: "半 (half) 途 (the road) 而 (and) 废 (abandon) — to abandon something halfway along the road.",
    meaning: "To give up on something before finishing it. Paired with 有始有终 as its cautionary opposite.",
    meaningZh: {
      hanzi: "事情才做到一半，就没有耐心，不想再做下去了。",
      pinyin: "Shìqing cái zuò dào yíbàn, jiù méiyǒu nàixīn, bù xiǎng zài zuò xiàqù le.",
      charPinyin: ["shì", "qing", "cái", "zuò", "dào", "yí", "bàn", "", "jiù", "méi", "yǒu", "nài", "xīn", "", "bù", "xiǎng", "zài", "zuò", "xià", "qù", "le", ""],
    },
    dailyLifeScenario:
      "You and a friend start building a big LEGO set together, but halfway through your friend wants to stop and play something else instead of finishing it. You can gently remind them not to 半途而废.",
    exampleSentence: {
      hanzi: "爬山比赛中，山顶有奖牌，他因为太累，爬到一半就半途而废了。",
      pinyin: "Páshān bǐsài zhōng, shāndǐng yǒu jiǎngpái, tā yīnwèi tài lèi, pá dào yíbàn jiù bàntú'érfèi le.",
      english: "During the mountain-climbing competition, there was a medal waiting at the top — but because he got too tired, he gave up halfway up the mountain.",
      charPinyin: ["pá", "shān", "bǐ", "sài", "zhōng", "", "shān", "dǐng", "yǒu", "jiǎng", "pái", "", "tā", "yīn", "wèi", "tài", "lèi", "", "pá", "dào", "yí", "bàn", "jiù", "bàn", "tú", "ér", "fèi", "le", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning/origin (礼记·中庸, the 'weaver's wife' fable) confirmed via Baidu Baike and multiple 成语词典 sources.",
  },
  {
    id: "shu-neng-sheng-qiao",
    hanzi: "熟能生巧",
    pinyin: "shú néng shēng qiǎo",
    literalMeaning: "熟 (skilled/familiar) 能 (can) 生 (give rise to) 巧 (skill) — familiarity gives rise to skill.",
    meaning: "The more you practise something, the better and easier it becomes — practice makes perfect.",
    meaningZh: {
      hanzi: "一件事情做的次数多了，自然就会做得又快又好。",
      pinyin: "Yí jiàn shìqing zuò de cìshù duō le, zìrán jiù huì zuò de yòu kuài yòu hǎo.",
      charPinyin: ["yí", "jiàn", "shì", "qing", "zuò", "de", "cì", "shù", "duō", "le", "", "zì", "rán", "jiù", "huì", "zuò", "de", "yòu", "kuài", "yòu", "hǎo", ""],
    },
    dailyLifeScenario:
      "You keep dropping the ball the first few times you try basketball, but after practising every week, shooting hoops becomes easy. That's 熟能生巧.",
    exampleSentence: {
      hanzi: "他每天弹钢琴，现在弹得又快又准，熟能生巧。",
      pinyin: "Tā měitiān tán gāngqín, xiànzài tán de yòu kuài yòu zhǔn, shúnéngshēngqiǎo.",
      english: "He plays the piano every day, and now he plays quickly and accurately — practice really does make perfect.",
      charPinyin: ["tā", "měi", "tiān", "tán", "gāng", "qín", "", "xiàn", "zài", "tán", "de", "yòu", "kuài", "yòu", "zhǔn", "", "shú", "néng", "shēng", "qiǎo", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning confirmed via zdic.net; traced to the Northern Song 'oil-pourer' (卖油翁) story.",
  },
  {
    id: "mo-chu-cheng-zhen",
    hanzi: "磨杵成针",
    pinyin: "mó chǔ chéng zhēn",
    literalMeaning: "磨 (grind) 杵 (an iron rod) 成 (into) 针 (a needle) — grinding an iron rod into a sewing needle.",
    meaning: "With enough patience and persistence, even something that seems impossibly hard can be achieved.",
    meaningZh: {
      hanzi: "只要有耐心，肯不断努力，再困难的事情也能够做成。",
      pinyin: "Zhǐyào yǒu nàixīn, kěn búduàn nǔlì, zài kùnnán de shìqing yě nénggòu zuò chéng.",
      charPinyin: ["zhǐ", "yào", "yǒu", "nài", "xīn", "", "kěn", "bú", "duàn", "nǔ", "lì", "", "zài", "kùn", "nán", "de", "shì", "qing", "yě", "néng", "gòu", "zuò", "chéng", ""],
    },
    dailyLifeScenario:
      "You've been trying to master a difficult piece on the recorder for weeks and want to quit — a parent might tell you the story of 磨杵成针 to encourage you that persistence pays off.",
    exampleSentence: {
      hanzi: "他学不会骑自行车，可是每天坚持练习，几个月后终于学会了，这就是磨杵成针。",
      pinyin: "Tā xué bú huì qí zìxíngchē, kěshì měitiān jiānchí liànxí, jǐ ge yuè hòu zhōngyú xuéhuì le, zhè jiùshì móchǔ-chéngzhēn.",
      english: "He just couldn't learn to ride a bike no matter what, but he kept practicing every day, and months later he finally learned — that's turning an iron rod into a needle.",
      charPinyin: ["tā", "xué", "bú", "huì", "qí", "zì", "xíng", "chē", "", "kě", "shì", "měi", "tiān", "jiān", "chí", "liàn", "xí", "", "jǐ", "ge", "yuè", "hòu", "zhōng", "yú", "xué", "huì", "le", "", "zhè", "jiù", "shì", "mó", "chǔ", "chéng", "zhēn", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes:
      "Origin: the Li Bai childhood legend (宋·祝穆《方舆胜览》). Standard 4-character dictionary form used (some storybooks use the 5-character 铁杵磨成针 — same meaning/story).",
  },
  {
    id: "ba-miao-zhu-zhang",
    hanzi: "拔苗助长",
    pinyin: "bá miáo zhù zhǎng",
    literalMeaning: "拔 (pull up) 苗 (a seedling) 助 (help) 长 (grow) — pulling up seedlings to 'help' them grow.",
    meaning:
      "Trying to rush or force progress instead of letting it happen naturally ends up doing more harm than good.",
    meaningZh: {
      hanzi: "为了让事情快点完成而着急乱来，结果反而把事情弄得更糟。",
      pinyin: "Wèile ràng shìqing kuài diǎn wánchéng ér zháojí luàn lái, jiéguǒ fǎn'ér bǎ shìqing nòng de gèng zāo.",
      charPinyin: ["wèi", "le", "ràng", "shì", "qing", "kuài", "diǎn", "wán", "chéng", "ér", "zháo", "jí", "luàn", "lái", "", "jié", "guǒ", "fǎn", "ér", "bǎ", "shì", "qing", "nòng", "de", "gèng", "zāo", ""],
    },
    dailyLifeScenario:
      "You want to learn to ride a bicycle without training wheels right away, without practising the basics first, and keep falling. A parent might explain that rushing it is like 拔苗助长.",
    exampleSentence: {
      hanzi: "他的豆芽还没长高，他心急就把豆芽拔高了一些，结果豆芽枯死了，这就是拔苗助长。",
      pinyin: "Tā de dòuyá hái méi zhǎnggāo, tā xīnjí jiù bǎ dòuyá bágāo le yìxiē, jiéguǒ dòuyá kūsǐ le, zhè jiùshì bámiáo-zhùzhǎng.",
      english: "His bean sprouts hadn't grown tall yet; impatient, he pulled them up a bit himself — and the sprouts withered and died. That's exactly \"pulling up seedlings to help them grow.\"",
      charPinyin: ["tā", "de", "dòu", "yá", "hái", "méi", "zhǎng", "gāo", "", "tā", "xīn", "jí", "jiù", "bǎ", "dòu", "yá", "bá", "gāo", "le", "yì", "xiē", "", "jié", "guǒ", "dòu", "yá", "kū", "sǐ", "le", "", "zhè", "jiù", "shì", "bá", "miáo", "zhù", "zhǎng", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes:
      "Origin: 孟子·公孙丑上. Editorial note (approved 2026-08-06): classical/textbook form is 揠苗助长 (揠 is rare); 拔苗助长 is the simplified, far more commonly recognised colloquial variant, used here for readability.",
  },
  {
    id: "chi-zhi-yi-heng",
    hanzi: "持之以恒",
    pinyin: "chí zhī yǐ héng",
    literalMeaning: "持 (hold) 之 (it) 以 (with) 恒 (constancy) — holding onto something with constancy over time.",
    meaning: "To keep doing something steadily over a long time, without giving up.",
    meaningZh: {
      hanzi: "做事情要长期坚持，不能只有三分钟热度。",
      pinyin: "Zuò shìqing yào chángqī jiānchí, bù néng zhǐ yǒu sān fēnzhōng rèdù.",
      charPinyin: ["zuò", "shì", "qing", "yào", "cháng", "qī", "jiān", "chí", "", "bù", "néng", "zhǐ", "yǒu", "sān", "fēn", "zhōng", "rè", "dù", ""],
    },
    dailyLifeScenario:
      "You want to get better at jump rope, so you practise a little every single day after school for weeks, even on days you don't feel like it. That steady, ongoing effort is 持之以恒.",
    exampleSentence: {
      hanzi: "他每天坚持写日记，一年都没有间断，这就是持之以恒。",
      pinyin: "Tā měitiān jiānchí xiě rìjì, yìnián dōu méiyǒu jiànduàn, zhè jiùshì chízhī-yǐhéng.",
      english: "He kept writing in his diary every single day, without a single break for a whole year — that's what persisting steadily really means.",
      charPinyin: ["tā", "měi", "tiān", "jiān", "chí", "xiě", "rì", "jì", "", "yì", "nián", "dōu", "méi", "yǒu", "jiàn", "duàn", "", "zhè", "jiù", "shì", "chí", "zhī", "yǐ", "héng", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning/origin (清·曾国藩《家训谕纪泽》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "quan-shen-guan-zhu",
    hanzi: "全神贯注",
    pinyin: "quán shén guàn zhù",
    literalMeaning: "全 (entire) 神 (spirit/attention) 贯 (pour through) 注 (focus) — pouring your entire attention into one place.",
    meaning: "To concentrate so completely on something that nothing else can distract you.",
    meaningZh: {
      hanzi: "把全部的注意力都集中在一件事情上，什么都不会打扰到自己。",
      pinyin: "Bǎ quánbù de zhùyìlì dōu jízhōng zài yí jiàn shìqing shàng, shénme dōu bú huì dǎrǎo dào zìjǐ.",
      charPinyin: ["bǎ", "quán", "bù", "de", "zhù", "yì", "lì", "dōu", "jí", "zhōng", "zài", "yí", "jiàn", "shì", "qing", "shàng", "", "shén", "me", "dōu", "bú", "huì", "dǎ", "rǎo", "dào", "zì", "jǐ", ""],
    },
    dailyLifeScenario:
      "You're building a tall block tower and you're so focused on balancing each piece that you don't even hear your name being called from the next room. That total concentration is 全神贯注.",
    exampleSentence: {
      hanzi: "他全神贯注地搭积木，都没听到妈妈叫他。",
      pinyin: "Tā quánshén-guànzhù de dā jīmù, dōu méi tīngdào māma jiào tā.",
      english: "He was so focused on building his blocks that he didn't even hear his mum calling him.",
      charPinyin: ["tā", "quán", "shén", "guàn", "zhù", "de", "dā", "jī", "mù", "", "dōu", "méi", "tīng", "dào", "mā", "ma", "jiào", "tā", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-09 search); cited usage examples include Qian Zhongshu's 《围城》.",
  },
  {
    id: "yi-si-bu-gou",
    hanzi: "一丝不苟",
    pinyin: "yī sī bù gǒu",
    literalMeaning: "一 (a single) 丝 (thread) 不 (not) 苟 (careless) — not careless about even a single thread's width.",
    meaning: "Being extremely careful and serious about every small detail, never sloppy.",
    meaningZh: {
      hanzi: "做事情非常认真仔细，连最小的地方也不马虎。",
      pinyin: "Zuò shìqing fēicháng rènzhēn zǐxì, lián zuì xiǎo de dìfang yě bù mǎhu.",
      charPinyin: ["zuò", "shì", "qing", "fēi", "cháng", "rèn", "zhēn", "zǐ", "xì", "", "lián", "zuì", "xiǎo", "de", "dì", "fang", "yě", "bù", "mǎ", "hu", ""],
    },
    dailyLifeScenario:
      "When you copy your spelling words, you check every single stroke of every character carefully, instead of rushing and leaving some out. That careful attention to every detail is 一丝不苟.",
    exampleSentence: {
      hanzi: "他做完数学作业后，会仔细检查每一题，一丝不苟。",
      pinyin: "Tā zuò wán shùxué zuòyè hòu, huì zǐxì jiǎnchá měi yì tí, yìsī-bùgǒu.",
      english: "After finishing his math homework, he carefully checks every single question — meticulous, never sloppy.",
      charPinyin: ["tā", "zuò", "wán", "shù", "xué", "zuò", "yè", "hòu", "", "huì", "zǐ", "xì", "jiǎn", "chá", "měi", "yì", "tí", "", "yì", "sī", "bù", "gǒu", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-09 search); origin traced to 清·吴敬梓《儒林外史》.",
  },
  {
    id: "jing-yi-qiu-jing",
    hanzi: "精益求精",
    pinyin: "jīng yì qiú jīng",
    literalMeaning: "精 (excellent) 益 (even more) 求 (seek) 精 (excellence) — already excellent, yet still seeking to be even better.",
    meaning: "Not settling for \"good enough\" — always trying to make something you're already good at even better.",
    meaningZh: {
      hanzi: "已经做得很好了，还要求自己做得更好。",
      pinyin: "Yǐjīng zuò de hěn hǎo le, hái yāoqiú zìjǐ zuò de gèng hǎo.",
      charPinyin: ["yǐ", "jīng", "zuò", "de", "hěn", "hǎo", "le", "", "hái", "yāo", "qiú", "zì", "jǐ", "zuò", "de", "gèng", "hǎo", ""],
    },
    dailyLifeScenario:
      "Your drawing of a dragon already won a merit sticker, but you keep practising to make the wings and scales look even better next time, instead of stopping there. That drive to improve on something already good is 精益求精.",
    exampleSentence: {
      hanzi: "他的画已经很好了，但他还精益求精，把每一个细节都画得更仔细。",
      pinyin: "Tā de huà yǐjīng hěn hǎo le, dàn tā hái jīngyì-qiújīng, bǎ měi yí ge xìjié dōu huà de gèng zǐxì.",
      english: "His drawing was already very good, but he kept perfecting it, making every single detail even more careful.",
      charPinyin: ["tā", "de", "huà", "yǐ", "jīng", "hěn", "hǎo", "le", "", "dàn", "tā", "hái", "jīng", "yì", "qiú", "jīng", "", "bǎ", "měi", "yí", "ge", "xì", "jié", "dōu", "huà", "de", "gèng", "zǐ", "xì", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning/origin (论语·学而, by way of 朱熹's commentary) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "you-tiao-bu-wen",
    hanzi: "有条不紊",
    pinyin: "yǒu tiáo bù wěn",
    literalMeaning: "有 (have) 条 (order) 不 (not) 紊 (chaotic) — having order to it, not chaotic.",
    meaning: "Doing things in an organized, methodical way — everything in its proper order, nothing chaotic.",
    meaningZh: {
      hanzi: "做事情很有次序，一步一步来，不会乱七八糟。",
      pinyin: "Zuò shìqing hěn yǒu cìxù, yí bù yí bù lái, bú huì luànqībāzāo.",
      charPinyin: ["zuò", "shì", "qing", "hěn", "yǒu", "cì", "xù", "", "yí", "bù", "yí", "bù", "lái", "", "bú", "huì", "luàn", "qī", "bā", "zāo", ""],
    },
    dailyLifeScenario:
      "You tidy your room by putting toys in one box, books on the shelf, and clothes in the drawer, one thing at a time, instead of just shoving everything in a pile. That organized way of doing it is 有条不紊.",
    exampleSentence: {
      hanzi: "整理书包时，他有条不紊，把每样东西都放回原位。",
      pinyin: "Zhěnglǐ shūbāo shí, tā yǒutiáo-bùwěn, bǎ měi yàng dōngxi dōu fàng huí yuánwèi.",
      english: "When packing his school bag, he's methodical — he puts every single thing back in its proper place.",
      charPinyin: ["zhěng", "lǐ", "shū", "bāo", "shí", "", "tā", "yǒu", "tiáo", "bù", "wěn", "", "bǎ", "měi", "yàng", "dōng", "xi", "dōu", "fàng", "huí", "yuán", "wèi", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning/origin (《尚书·盘庚上》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "chu-bian-bu-jing",
    hanzi: "处变不惊",
    pinyin: "chǔ biàn bù jīng",
    literalMeaning: "处 (face) 变 (a sudden change) 不 (not) 惊 (panic) — facing a sudden change without panicking.",
    meaning: "Staying calm and steady even when something unexpected or alarming suddenly happens.",
    meaningZh: {
      hanzi: "遇到突然发生的事情，也能保持冷静，不慌张。",
      pinyin: "Yùdào tūrán fāshēng de shìqing, yě néng bǎochí lěngjìng, bù huāngzhāng.",
      charPinyin: ["yù", "dào", "tū", "rán", "fā", "shēng", "de", "shì", "qing", "", "yě", "néng", "bǎo", "chí", "lěng", "jìng", "", "bù", "huāng", "zhāng", ""],
    },
    dailyLifeScenario:
      "During a class presentation, you suddenly forget your next line in front of everyone — instead of panicking, you take a breath, glance at your notes, and calmly continue. That steady calm under pressure is 处变不惊.",
    exampleSentence: {
      hanzi: "台上突然停电，他处变不惊，冷静地继续表演。",
      pinyin: "Táishàng tūrán tíngdiàn, tā chǔbiàn-bùjīng, lěngjìng de jìxù biǎoyǎn.",
      english: "The power suddenly went out on stage, but he stayed calm and steady, and kept performing without missing a beat.",
      charPinyin: ["tái", "shàng", "tū", "rán", "tíng", "diàn", "", "tā", "chǔ", "biàn", "bù", "jīng", "", "lěng", "jìng", "de", "jì", "xù", "biǎo", "yǎn", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-10 search); Taiwan MOE 成語典 entry also confirms the reading and usage.",
  },
  {
    id: "quan-li-yi-fu",
    hanzi: "全力以赴",
    pinyin: "quán lì yǐ fù",
    literalMeaning: "全 (all) 力 (strength) 以 (with) 赴 (throw oneself into) — throwing all one's strength into it.",
    meaning: "Giving something everything you've got, holding nothing back.",
    meaningZh: {
      hanzi: "把所有的力气和精神都用上，一点也不保留。",
      pinyin: "Bǎ suǒyǒu de lìqi hé jīngshén dōu yòng shàng, yìdiǎn yě bù bǎoliú.",
      charPinyin: ["bǎ", "suǒ", "yǒu", "de", "lì", "qi", "hé", "jīng", "shén", "dōu", "yòng", "shàng", "", "yì", "diǎn", "yě", "bù", "bǎo", "liú", ""],
    },
    dailyLifeScenario:
      "It's the final race of Sports Day, and even though your legs are tired, you push as hard as you possibly can all the way to the finish line, holding nothing back. That's giving it 全力以赴.",
    exampleSentence: {
      hanzi: "运动会接力赛时，他全力以赴，冲过了终点线。",
      pinyin: "Yùndònghuì jiēlìsài shí, tā quánlì-yǐfù, chōngguò le zhōngdiǎnxiàn.",
      english: "During the relay race on Sports Day, he gave it everything he had and sprinted across the finish line.",
      charPinyin: ["yùn", "dòng", "huì", "jiē", "lì", "sài", "shí", "", "tā", "quán", "lì", "yǐ", "fù", "", "chōng", "guò", "le", "zhōng", "diǎn", "xiàn", ""],
    },
    ageBand: "lower-primary",
    theme: "focus",
    sourceNotes: "Meaning/origin (清·赵翼《廿二史札记》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },

  // --- Honesty & Character ---
  {
    id: "yan-er-you-xin",
    hanzi: "言而有信",
    pinyin: "yán ér yǒu xìn",
    literalMeaning: "言 (words) 而 (and) 有 (have) 信 (trust) — your words come with trustworthiness.",
    meaning: "Keeping your promises; being someone whose word can be trusted.",
    meaningZh: {
      hanzi: "答应别人的事情，一定会做到，是个说话算话的人。",
      pinyin: "Dāying biérén de shìqing, yídìng huì zuò dào, shì ge shuōhuà suànhuà de rén.",
      charPinyin: ["dā", "ying", "bié", "rén", "de", "shì", "qing", "", "yí", "dìng", "huì", "zuò", "dào", "", "shì", "ge", "shuō", "huà", "suàn", "huà", "de", "rén", ""],
    },
    dailyLifeScenario:
      "You promise your friend you'll bring your favourite storybook to school to lend them tomorrow — and you actually remember to bring it. That's being 言而有信.",
    exampleSentence: {
      hanzi: "他答应借我漫画书，第二天真的带来了，真是言而有信。",
      pinyin: "Tā dāying jiè wǒ mànhuàshū, dì-èr tiān zhēn de dài lái le, zhēnshi yán'éryǒuxìn.",
      english: "He promised to lend me his comic book, and really brought it the next day.",
      charPinyin: ["tā", "dā", "ying", "jiè", "wǒ", "màn", "huà", "shū", "", "dì", "èr", "tiān", "zhēn", "de", "dài", "lái", "le", "", "zhēn", "shi", "yán", "ér", "yǒu", "xìn", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes:
      "Origin: 论语·学而 (Zixia's teaching on trustworthy speech). Chosen over 一诺千金 because its characters (言/信) are more direct for this age group.",
  },
  {
    id: "zhi-cuo-jiu-gai",
    hanzi: "知错就改",
    pinyin: "zhī cuò jiù gǎi",
    literalMeaning: "知 (know) 错 (mistake) 就 (then) 改 (correct) — knowing your mistake, and correcting it right away.",
    meaning: "Admitting when you've made a mistake and fixing it, instead of hiding it or making excuses.",
    meaningZh: {
      hanzi: "发现自己做错了事，马上承认并且改正，不找借口。",
      pinyin: "Fāxiàn zìjǐ zuò cuò le shì, mǎshàng chéngrèn bìngqiě gǎizhèng, bù zhǎo jièkǒu.",
      charPinyin: ["fā", "xiàn", "zì", "jǐ", "zuò", "cuò", "le", "shì", "", "mǎ", "shàng", "chéng", "rèn", "bìng", "qiě", "gǎi", "zhèng", "", "bù", "zhǎo", "jiè", "kǒu", ""],
    },
    dailyLifeScenario:
      "You accidentally knock over your sister's block tower while running around the house. Instead of blaming her or walking away, you say sorry and help rebuild it — that's 知错就改.",
    exampleSentence: {
      hanzi: "他发现自己把数学题算错了，知错就改，马上把答案改了过来。",
      pinyin: "Tā fāxiàn zìjǐ bǎ shùxué tí suàncuò le, zhīcuò-jiùgǎi, mǎshàng bǎ dá'àn gǎi le guòlái.",
      english: "He realized he'd calculated a math problem wrong — recognizing the mistake, he corrected it, fixing the answer right away.",
      charPinyin: ["tā", "fā", "xiàn", "zì", "jǐ", "bǎ", "shù", "xué", "tí", "suàn", "cuò", "le", "", "zhī", "cuò", "jiù", "gǎi", "", "mǎ", "shàng", "bǎ", "dá", "àn", "gǎi", "le", "guò", "lái", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes:
      "Confirmed across multiple 成语词典; derives from 知错能改，善莫大焉 (左传·宣公二年), also listed at primary-school level by Hong Kong's Education Bureau.",
  },
  {
    id: "shi-shi-qiu-shi",
    hanzi: "实事求是",
    pinyin: "shí shì qiú shì",
    literalMeaning: "实 (real) 事 (facts) 求 (seek) 是 (the truth) — seeking the truth from real facts.",
    meaning: "Looking at what's actually true and going by the real facts, instead of guessing or making things up.",
    meaningZh: {
      hanzi: "根据真实的情况说话做事，不夸大也不隐瞒。",
      pinyin: "Gēnjù zhēnshí de qíngkuàng shuōhuà zuòshì, bù kuādà yě bù yǐnmán.",
      charPinyin: ["gēn", "jù", "zhēn", "shí", "de", "qíng", "kuàng", "shuō", "huà", "zuò", "shì", "", "bù", "kuā", "dà", "yě", "bù", "yǐn", "mán", ""],
    },
    dailyLifeScenario:
      "You accidentally spill juice on the carpet. When your mum asks what happened, you tell her exactly what you did instead of blaming the cat or making up a story. That's being 实事求是.",
    exampleSentence: {
      hanzi: "做实验的时候，他实事求是，只记录真正看到的结果，不会乱猜。",
      pinyin: "Zuò shíyàn de shíhou, tā shíshì-qiúshì, zhǐ jìlù zhēnzhèng kàndào de jiéguǒ, bú huì luàn cāi.",
      english: "During the experiment, he stuck to the facts — recording only what he actually observed, not guessing wildly.",
      charPinyin: ["zuò", "shí", "yàn", "de", "shí", "hou", "", "tā", "shí", "shì", "qiú", "shì", "", "zhǐ", "jì", "lù", "zhēn", "zhèng", "kàn", "dào", "de", "jié", "guǒ", "", "bú", "huì", "luàn", "cāi", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning/origin (《汉书·河间献王刘德传》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "guang-ming-zheng-da",
    hanzi: "光明正大",
    pinyin: "guāng míng zhèng dà",
    literalMeaning: "光 (light) 明 (bright) 正 (upright) 大 (great) — bright and upright, open and fair.",
    meaning: "Being open, honest, and fair in what you do — nothing sneaky or hidden.",
    meaningZh: {
      hanzi: "做事情坦白公正，没有偷偷摸摸的坏心思。",
      pinyin: "Zuò shìqing tǎnbái gōngzhèng, méiyǒu tōutōumōmō de huài xīnsi.",
      charPinyin: ["zuò", "shì", "qing", "tǎn", "bái", "gōng", "zhèng", "", "méi", "yǒu", "tōu", "tōu", "mō", "mō", "de", "huài", "xīn", "si", ""],
    },
    dailyLifeScenario:
      "During a board game, you could peek at the cards when no one's looking, but instead you play fair and follow all the rules openly. That's being 光明正大.",
    exampleSentence: {
      hanzi: "考试的时候，他光明正大，从来不偷看别人的答案。",
      pinyin: "Kǎoshì de shíhou, tā guāngmíng-zhèngdà, cónglái bù tōukàn biérén de dá'àn.",
      english: "During exams, he's always open and fair — he never sneaks a look at other people's answers.",
      charPinyin: ["kǎo", "shì", "de", "shí", "hou", "", "tā", "guāng", "míng", "zhèng", "dà", "", "cóng", "lái", "bù", "tōu", "kàn", "bié", "rén", "de", "dá", "àn", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning/origin (宋·朱熹《朱子语类》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "biao-li-ru-yi",
    hanzi: "表里如一",
    pinyin: "biǎo lǐ rú yī",
    literalMeaning: "表 (the outside) 里 (the inside) 如 (is like) 一 (one) — the outside matches the inside, as if they were one.",
    meaning: "Being the same genuine person on the inside as you show on the outside — not pretending to be someone you're not.",
    meaningZh: {
      hanzi: "心里想的和表现出来的完全一样，不假装。",
      pinyin: "Xīnli xiǎng de hé biǎoxiàn chūlái de wánquán yíyàng, bù jiǎzhuāng.",
      charPinyin: ["xīn", "li", "xiǎng", "de", "hé", "biǎo", "xiàn", "chū", "lái", "de", "wán", "quán", "yí", "yàng", "", "bù", "jiǎ", "zhuāng", ""],
    },
    dailyLifeScenario:
      "You tell your friends you love reading, and at home, when no one's watching, you really do curl up with a book too — not just pretending to like it in front of others. That's being 表里如一.",
    exampleSentence: {
      hanzi: "他表里如一，在家和在学校对人一样友善。",
      pinyin: "Tā biǎolǐ-rúyī, zài jiā hé zài xuéxiào duì rén yíyàng yǒushàn.",
      english: "He's the same person inside and out — just as kind to people at home as he is at school.",
      charPinyin: ["tā", "biǎo", "lǐ", "rú", "yī", "", "zài", "jiā", "hé", "zài", "xué", "xiào", "duì", "rén", "yí", "yàng", "yǒu", "shàn", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning/origin (《朱子全书·论语》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "cheng-xin-cheng-yi",
    hanzi: "诚心诚意",
    pinyin: "chéng xīn chéng yì",
    literalMeaning: "诚 (sincere) 心 (heart) 诚 (sincere) 意 (intention) — a heart and intention that are truly sincere.",
    meaning: "Doing or saying something with complete sincerity, really meaning it, not just for show.",
    meaningZh: {
      hanzi: "真心实意地对人对事，不是随便做做样子。",
      pinyin: "Zhēnxīn-shíyì de duì rén duì shì, bú shì suíbiàn zuòzuo yàngzi.",
      charPinyin: ["zhēn", "xīn", "shí", "yì", "de", "duì", "rén", "duì", "shì", "", "bú", "shì", "suí", "biàn", "zuò", "zuo", "yàng", "zi", ""],
    },
    dailyLifeScenario:
      "You write a birthday card for your grandma, thinking carefully about what to say because you really mean every word — not just scribbling something quickly to get it over with. That's 诚心诚意.",
    exampleSentence: {
      hanzi: "他诚心诚意地向奶奶道歉，奶奶原谅了他。",
      pinyin: "Tā chéngxīn-chéngyì de xiàng nǎinai dàoqiàn, nǎinai yuánliàng le tā.",
      english: "He apologised to Grandma with complete sincerity, and Grandma forgave him.",
      charPinyin: ["tā", "chéng", "xīn", "chéng", "yì", "de", "xiàng", "nǎi", "nai", "dào", "qiàn", "", "nǎi", "nai", "yuán", "liàng", "le", "tā", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning confirmed via zdic.net (origin traced to 《后汉书·马援传》); Baidu Baike cross-check 2026-09-09.",
  },
  {
    id: "qian-xu-jin-shen",
    hanzi: "谦虚谨慎",
    pinyin: "qiān xū jǐn shèn",
    literalMeaning: "谦 (modest) 虚 (humble) 谨 (careful) 慎 (cautious) — modest and humble, careful and cautious.",
    meaning: "Being humble about what you're good at, and careful/thoughtful rather than boastful or careless.",
    meaningZh: {
      hanzi: "不骄傲自大，做事说话都小心，不随便夸耀自己。",
      pinyin: "Bù jiāo'ào zìdà, zuò shì shuō huà dōu xiǎoxīn, bù suíbiàn kuāyào zìjǐ.",
      charPinyin: ["bù", "jiāo", "ào", "zì", "dà", "", "zuò", "shì", "shuō", "huà", "dōu", "xiǎo", "xīn", "", "bù", "suí", "biàn", "kuā", "yào", "zì", "jǐ", ""],
    },
    dailyLifeScenario:
      "You won first place in the spelling competition, but instead of bragging about it, you quietly thank your teacher and keep practising just as carefully as before. That humble, careful attitude is 谦虚谨慎.",
    exampleSentence: {
      hanzi: "得了第一名，他还是谦虚谨慎，没有到处炫耀。",
      pinyin: "Déle dì-yī míng, tā háishi qiānxū-jǐnshèn, méiyǒu dàochù xuànyào.",
      english: "Even after winning first place, he stayed humble and careful, instead of showing off to everyone.",
      charPinyin: ["dé", "le", "dì", "yī", "míng", "", "tā", "hái", "shi", "qiān", "xū", "jǐn", "shèn", "", "méi", "yǒu", "dào", "chù", "xuàn", "yào", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning/origin (《晋书·张宾载记》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "zhi-en-tu-bao",
    hanzi: "知恩图报",
    pinyin: "zhī ēn tú bào",
    literalMeaning: "知 (know) 恩 (kindness received) 图 (plan to) 报 (repay) — knowing a kindness done to you, and planning to repay it.",
    meaning: "Remembering when someone has helped you, and looking for a way to repay their kindness.",
    meaningZh: {
      hanzi: "记得别人对自己的好，并且想办法回报他。",
      pinyin: "Jìde biérén duì zìjǐ de hǎo, bìngqiě xiǎng bànfǎ huíbào tā.",
      charPinyin: ["jì", "de", "bié", "rén", "duì", "zì", "jǐ", "de", "hǎo", "", "bìng", "qiě", "xiǎng", "bàn", "fǎ", "huí", "bào", "tā", ""],
    },
    dailyLifeScenario:
      "Your neighbour helped you find your lost cat last month, so this weekend you bake some cookies and bring them over to say thank you. Remembering and repaying that kindness is 知恩图报.",
    exampleSentence: {
      hanzi: "邻居曾经帮过他，他知恩图报，做了饼干送去感谢。",
      pinyin: "Línjū céngjīng bāngguò tā, tā zhī'ēn-túbào, zuò le bǐnggān sòng qù gǎnxiè.",
      english: "His neighbour had once helped him, so he remembered and repaid that kindness by baking cookies to say thanks.",
      charPinyin: ["lín", "jū", "céng", "jīng", "bāng", "guò", "tā", "", "tā", "zhī", "ēn", "tú", "bào", "", "zuò", "le", "bǐng", "gān", "sòng", "qù", "gǎn", "xiè", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning confirmed via Baidu Baike and multiple 成语词典 aggregators (early form traced to the Spring-and-Autumn-era Zhao Xuanzi/Ling Zhe story; later usage in 元·李致远《还牢末》); 2026-09-10 search.",
  },
  {
    id: "yan-yu-lv-ji",
    hanzi: "严于律己",
    pinyin: "yán yú lǜ jǐ",
    literalMeaning: "严 (strict) 于 (with) 律 (regulate) 己 (oneself) — being strict with yourself, holding yourself to a high standard.",
    meaning: "Holding yourself to strict, high standards — even when nobody's watching.",
    meaningZh: {
      hanzi: "对自己的要求很严格，不放松，不找借口。",
      pinyin: "Duì zìjǐ de yāoqiú hěn yángé, bú fàngsōng, bù zhǎo jièkǒu.",
      charPinyin: ["duì", "zì", "jǐ", "de", "yāo", "qiú", "hěn", "yán", "gé", "", "bú", "fàng", "sōng", "", "bù", "zhǎo", "jiè", "kǒu", ""],
    },
    dailyLifeScenario:
      "Nobody would notice if you skipped the last few questions on your practice worksheet, but you finish every single one anyway, because that's the standard you hold yourself to. That's 严于律己.",
    exampleSentence: {
      hanzi: "就算没有人检查，他也严于律己，认真做完每一题。",
      pinyin: "Jiùsuàn méiyǒu rén jiǎnchá, tā yě yányú-lǜjǐ, rènzhēn zuò wán měi yì tí.",
      english: "Even with no one checking, he still held himself to a strict standard and carefully finished every question.",
      charPinyin: ["jiù", "suàn", "méi", "yǒu", "rén", "jiǎn", "chá", "", "tā", "yě", "yán", "yú", "lǜ", "jǐ", "", "rèn", "zhēn", "zuò", "wán", "měi", "yì", "tí", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-10 search); traditionally paired with 宽以待人 (宋·陈亮《谢曾察院启》), used standalone here for a single clear lesson.",
  },
  {
    id: "kuan-yi-dai-ren",
    hanzi: "宽以待人",
    pinyin: "kuān yǐ dài rén",
    literalMeaning: "宽 (generous) 以 (with) 待 (treat) 人 (people) — treating people with generosity and tolerance.",
    meaning: "Being patient, forgiving, and generous toward others, instead of being harsh or quick to judge.",
    meaningZh: {
      hanzi: "对别人宽容大方，不轻易责怪别人的小错。",
      pinyin: "Duì biérén kuānróng dàfāng, bù qīngyì zéguài biérén de xiǎo cuò.",
      charPinyin: ["duì", "bié", "rén", "kuān", "róng", "dà", "fāng", "", "bù", "qīng", "yì", "zé", "guài", "bié", "rén", "de", "xiǎo", "cuò", ""],
    },
    dailyLifeScenario:
      "Your friend accidentally breaks your favourite pencil while borrowing it. Instead of getting angry, you tell them it's okay and it was just an accident. That patient, forgiving attitude is 宽以待人.",
    exampleSentence: {
      hanzi: "朋友不小心弄坏了他的东西，他宽以待人，没有生气。",
      pinyin: "Péngyou bù xiǎoxīn nòng huài le tā de dōngxi, tā kuānyǐ-dàirén, méiyǒu shēngqì.",
      english: "A friend accidentally broke his thing, but he was patient and forgiving, and didn't get angry.",
      charPinyin: ["péng", "you", "bù", "xiǎo", "xīn", "nòng", "huài", "le", "tā", "de", "dōng", "xi", "", "tā", "kuān", "yǐ", "dài", "rén", "", "méi", "yǒu", "shēng", "qì", ""],
    },
    ageBand: "lower-primary",
    theme: "honesty",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-10 search); origin traced to 罗贯中《三国演义》第60回, traditionally paired with 严于律己.",
  },

  // --- Kindness & Community ---
  {
    id: "zhu-ren-wei-le",
    hanzi: "助人为乐",
    pinyin: "zhù rén wéi lè",
    literalMeaning: "助 (help) 人 (people) 为 (is) 乐 (joy) — helping people is a source of joy.",
    meaning: "Finding happiness in helping others, and doing so willingly.",
    meaningZh: {
      hanzi: "看到别人需要帮忙的时候，很乐意伸出手去帮助他。",
      pinyin: "Kàndào biérén xūyào bāngmáng de shíhou, hěn lèyì shēnchū shǒu qù bāngzhù tā.",
      charPinyin: ["kàn", "dào", "bié", "rén", "xū", "yào", "bāng", "máng", "de", "shí", "hou", "", "hěn", "lè", "yì", "shēn", "chū", "shǒu", "qù", "bāng", "zhù", "tā", ""],
    },
    dailyLifeScenario:
      "At recess, you see a classmate trip and drop all their books. Instead of walking past, you stop to help pick them up — that's living out 助人为乐.",
    exampleSentence: {
      hanzi: "小华助人为乐，看到同学摔倒了马上跑过去扶他，心里觉得很开心。",
      pinyin: "Xiǎohuá zhùrén-wéilè, kàndào tóngxué shuāidǎo le mǎshàng pǎo guòqù fú tā, xīnli juéde hěn kāixīn.",
      english: "Xiaohua loves helping others — he ran to help a classmate up right away, and it made him happy.",
      charPinyin: ["xiǎo", "huá", "zhù", "rén", "wéi", "lè", "", "kàn", "dào", "tóng", "xué", "shuāi", "dǎo", "le", "mǎ", "shàng", "pǎo", "guò", "qù", "fú", "tā", "", "xīn", "li", "jué", "de", "hěn", "kāi", "xīn", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Confirmed via zdic.net and Baidu Baike; appears in Malaysian KSSR-aligned idiom compilations for primary students.",
  },
  {
    id: "qi-xin-xie-li",
    hanzi: "齐心协力",
    pinyin: "qí xīn xié lì",
    literalMeaning: "齐 (together) 心 (hearts) 协 (join) 力 (strength) — hearts aligned, strength joined together.",
    meaning: "Working together as a team toward the same goal.",
    meaningZh: {
      hanzi: "大家一起合作，共同努力，去完成同一个目标。",
      pinyin: "Dàjiā yìqǐ hézuò, gòngtóng nǔlì, qù wánchéng tóng yí ge mùbiāo.",
      charPinyin: ["dà", "jiā", "yì", "qǐ", "hé", "zuò", "", "gòng", "tóng", "nǔ", "lì", "", "qù", "wán", "chéng", "tóng", "yí", "ge", "mù", "biāo", ""],
    },
    dailyLifeScenario:
      "Your class needs to build a model volcano for a science project. If everyone in the group pitches in instead of arguing over who does what, you're showing 齐心协力.",
    exampleSentence: {
      hanzi: "我们小组齐心协力，终于把手工作品做好了。",
      pinyin: "Wǒmen xiǎozǔ qíxīn-xiélì, zhōngyú bǎ shǒugōng zuòpǐn zuò hǎo le.",
      english: "Our group worked together with one heart, and finished our craft project.",
      charPinyin: ["wǒ", "men", "xiǎo", "zǔ", "qí", "xīn", "xié", "lì", "", "zhōng", "yú", "bǎ", "shǒu", "gōng", "zuò", "pǐn", "zuò", "hǎo", "le", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Confirmed via zdic.net and Baidu Baike (origin: 墨子·尚贤).",
  },
  {
    id: "xiang-qin-xiang-ai",
    hanzi: "相亲相爱",
    pinyin: "xiāng qīn xiāng ài",
    literalMeaning: "相 (mutually) 亲 (be close) 相 (mutually) 爱 (love) — being mutually close and loving toward one another.",
    meaning: "People who care deeply for each other and treat each other with love — especially family.",
    meaningZh: {
      hanzi: "家人之间互相关心，互相疼爱，感情非常好。",
      pinyin: "Jiārén zhījiān hùxiāng guānxīn, hùxiāng téng'ài, gǎnqíng fēicháng hǎo.",
      charPinyin: ["jiā", "rén", "zhī", "jiān", "hù", "xiāng", "guān", "xīn", "", "hù", "xiāng", "téng", "ài", "", "gǎn", "qíng", "fēi", "cháng", "hǎo", ""],
    },
    dailyLifeScenario:
      "On the weekend, your whole family cooks a meal together and shares stories at the dinner table, looking out for one another. That warm feeling is 相亲相爱.",
    exampleSentence: {
      hanzi: "我们一家人相亲相爱，不管遇到什么困难都会互相帮助。",
      pinyin: "Wǒmen yìjiā rén xiāngqīn-xiāng'ài, bùguǎn yùdào shénme kùnnán dōu huì hùxiāng bāngzhù.",
      english: "Our family loves and cares for each other, no matter what difficulty we face.",
      charPinyin: ["wǒ", "men", "yì", "jiā", "rén", "xiāng", "qīn", "xiāng", "ài", "", "bù", "guǎn", "yù", "dào", "shén", "me", "kùn", "nán", "dōu", "huì", "hù", "xiāng", "bāng", "zhù", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes:
      "Editorial note (approved 2026-08-06): formal dictionary usage notes it as traditionally 'between spouses,' but '相亲相爱一家人' is extremely common in modern usage for whole families (family-day slogans, a well-known children's song) — extended here to sibling/family love.",
  },
  {
    id: "jian-yi-yong-wei",
    hanzi: "见义勇为",
    pinyin: "jiàn yì yǒng wéi",
    literalMeaning: "见 (see) 义 (what's right) 勇 (bravely) 为 (do) — seeing what's right, and bravely doing it.",
    meaning: "Bravely stepping in to do the right thing when you see someone in trouble or something unfair happening.",
    meaningZh: {
      hanzi: "看到不公平或者危险的事情，勇敢地站出来帮忙。",
      pinyin: "Kàndào bù gōngpíng huòzhě wēixiǎn de shìqing, yǒnggǎn de zhàn chūlái bāngmáng.",
      charPinyin: ["kàn", "dào", "bù", "gōng", "píng", "huò", "zhě", "wēi", "xiǎn", "de", "shì", "qing", "", "yǒng", "gǎn", "de", "zhàn", "chū", "lái", "bāng", "máng", ""],
    },
    dailyLifeScenario:
      "You see a younger kid at the playground being teased by an older group. Even though it's a bit scary, you speak up and tell them to stop. That brave stand for what's right is 见义勇为.",
    exampleSentence: {
      hanzi: "看到同学被欺负，他见义勇为，勇敢地站出来帮忙。",
      pinyin: "Kàndào tóngxué bèi qīfù, tā jiànyì-yǒngwéi, yǒnggǎn de zhàn chūlái bāngmáng.",
      english: "When he saw a classmate being bullied, he bravely stepped up to do the right thing and help.",
      charPinyin: ["kàn", "dào", "tóng", "xué", "bèi", "qī", "fù", "", "tā", "jiàn", "yì", "yǒng", "wéi", "", "yǒng", "gǎn", "de", "zhàn", "chū", "lái", "bāng", "máng", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning/origin (《论语·为政》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "xue-zhong-song-tan",
    hanzi: "雪中送炭",
    pinyin: "xuě zhōng sòng tàn",
    literalMeaning: "雪 (snow) 中 (amid) 送 (deliver) 炭 (charcoal) — delivering charcoal to someone in the middle of a snowstorm.",
    meaning: "Helping someone exactly when they need it most, in a hard or difficult moment.",
    meaningZh: {
      hanzi: "在别人最困难的时候，及时伸出援手帮助他。",
      pinyin: "Zài biérén zuì kùnnán de shíhou, jíshí shēnchū yuánshǒu bāngzhù tā.",
      charPinyin: ["zài", "bié", "rén", "zuì", "kùn", "nán", "de", "shí", "hou", "", "jí", "shí", "shēn", "chū", "yuán", "shǒu", "bāng", "zhù", "tā", ""],
    },
    dailyLifeScenario:
      "Your classmate forgot their umbrella on a rainy day and has no way to get home. You share yours with them right when they need it most, instead of just walking off. That's 雪中送炭.",
    exampleSentence: {
      hanzi: "同学忘记带伞，下雨天他雪中送炭，把伞借给同学。",
      pinyin: "Tóngxué wàngjì dài sǎn, xiàyǔ tiān tā xuězhōng-sòngtàn, bǎ sǎn jiè gěi tóngxué.",
      english: "A classmate forgot his umbrella on a rainy day, so he helped exactly when it was needed and lent him his own.",
      charPinyin: ["tóng", "xué", "wàng", "jì", "dài", "sǎn", "", "xià", "yǔ", "tiān", "tā", "xuě", "zhōng", "sòng", "tàn", "", "bǎ", "sǎn", "jiè", "gěi", "tóng", "xué", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning/origin (宋·范成大《大雪送炭与芥隐》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "tong-gan-gong-ku",
    hanzi: "同甘共苦",
    pinyin: "tóng gān gòng kǔ",
    literalMeaning: "同 (together) 甘 (sweetness) 共 (share) 苦 (bitterness) — sharing both the sweet times and the bitter times together.",
    meaning: "Staying together and supporting each other through both the good times and the hard times.",
    meaningZh: {
      hanzi: "不管遇到开心的事还是困难的事，都一起面对，互相扶持。",
      pinyin: "Bùguǎn yùdào kāixīn de shì háishi kùnnán de shì, dōu yìqǐ miànduì, hùxiāng fúchí.",
      charPinyin: ["bù", "guǎn", "yù", "dào", "kāi", "xīn", "de", "shì", "hái", "shi", "kùn", "nán", "de", "shì", "", "dōu", "yì", "qǐ", "miàn", "duì", "", "hù", "xiāng", "fú", "chí", ""],
    },
    dailyLifeScenario:
      "Your football team loses badly in the first half but you all cheer each other up and give it your all together in the second half — win or lose, you stick together. That's 同甘共苦.",
    exampleSentence: {
      hanzi: "队友之间同甘共苦，输球时也互相鼓励。",
      pinyin: "Duìyǒu zhījiān tónggān-gòngkǔ, shūqiú shí yě hùxiāng gǔlì.",
      english: "Teammates share both good times and hard times — even after losing a match, they still cheer each other on.",
      charPinyin: ["duì", "yǒu", "zhī", "jiān", "tóng", "gān", "gòng", "kǔ", "", "shū", "qiú", "shí", "yě", "hù", "xiāng", "gǔ", "lì", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning/origin (《战国策·燕策一》, the Yan Zhaowang story) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "fu-lao-xie-you",
    hanzi: "扶老携幼",
    pinyin: "fú lǎo xié yòu",
    literalMeaning: "扶 (support) 老 (the elderly) 携 (lead by hand) 幼 (the young) — supporting the elderly and leading the young by the hand.",
    meaning: "Everyone helping and caring for each other across generations — supporting the old and looking after the young together.",
    meaningZh: {
      hanzi: "大家一起出门的时候，照顾年纪大的和年纪小的。",
      pinyin: "Dàjiā yìqǐ chūmén de shíhou, zhàogù niánjì dà de hé niánjì xiǎo de.",
      charPinyin: ["dà", "jiā", "yì", "qǐ", "chū", "mén", "de", "shí", "hou", "", "zhào", "gù", "nián", "jì", "dà", "de", "hé", "nián", "jì", "xiǎo", "de", ""],
    },
    dailyLifeScenario:
      "On a family hike, the big kids help grandma along the rocky path while also holding your little cousin's hand so nobody gets left behind. That caring for every generation together is 扶老携幼.",
    exampleSentence: {
      hanzi: "一家人去爬山，扶老携幼，互相照顾着走完全程。",
      pinyin: "Yìjiā rén qù páshān, fúlǎo-xiéyòu, hùxiāng zhàogù zhe zǒuwán quánchéng.",
      english: "The whole family went hiking, helping the old and looking after the young, caring for each other the whole way.",
      charPinyin: ["yì", "jiā", "rén", "qù", "pá", "shān", "", "fú", "lǎo", "xié", "yòu", "", "hù", "xiāng", "zhào", "gù", "zhe", "zǒu", "wán", "quán", "chéng", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning/origin (《战国策·齐策四》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "shou-zu-qing-shen",
    hanzi: "手足情深",
    pinyin: "shǒu zú qíng shēn",
    literalMeaning: "手 (hand) 足 (foot) 情 (affection) 深 (deep) — \"hands and feet\" (a classical way of referring to siblings), with deep affection between them.",
    meaning: "Deep, close affection between brothers and sisters.",
    meaningZh: {
      hanzi: "兄弟姐妹之间的感情很深厚，互相关心。",
      pinyin: "Xiōngdì jiěmèi zhījiān de gǎnqíng hěn shēnhòu, hùxiāng guānxīn.",
      charPinyin: ["xiōng", "dì", "jiě", "mèi", "zhī", "jiān", "de", "gǎn", "qíng", "hěn", "shēn", "hòu", "", "hù", "xiāng", "guān", "xīn", ""],
    },
    dailyLifeScenario:
      "Your older brother gives up his last piece of cake for you without even being asked, and you always look out for him too when he's upset. That closeness between siblings is 手足情深.",
    exampleSentence: {
      hanzi: "哥哥和弟弟手足情深，什么事都互相帮忙。",
      pinyin: "Gēge hé dìdi shǒuzú-qíngshēn, shénme shì dōu hùxiāng bāngmáng.",
      english: "The older and younger brother have deep sibling affection — they help each other with everything.",
      charPinyin: ["gē", "ge", "hé", "dì", "di", "shǒu", "zú", "qíng", "shēn", "", "shén", "me", "shì", "dōu", "hù", "xiāng", "bāng", "máng", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-10 search); classical usage traced to 唐·李华《吊古战场文》and 宋·苏辙《为兄轼下狱上书》.",
  },
  {
    id: "yu-ren-wei-shan",
    hanzi: "与人为善",
    pinyin: "yǔ rén wéi shàn",
    literalMeaning: "与 (with) 人 (people) 为 (do) 善 (good) — doing good together with others; treating people with kindness.",
    meaning: "Treating people with kindness and good intentions in how you interact with them, not just in big helpful acts.",
    meaningZh: {
      hanzi: "对待身边的人友善和气，抱着好意去相处。",
      pinyin: "Duìdài shēnbiān de rén yǒushàn héqi, bàozhe hǎoyì qù xiāngchǔ.",
      charPinyin: ["duì", "dài", "shēn", "biān", "de", "rén", "yǒu", "shàn", "hé", "qi", "", "bào", "zhe", "hǎo", "yì", "qù", "xiāng", "chǔ", ""],
    },
    dailyLifeScenario:
      "A new classmate seems shy and unsure on their first day, so you smile, say hello, and invite them to sit with you at lunch. Treating people with that kind of warmth is 与人为善.",
    exampleSentence: {
      hanzi: "对新同学，他与人为善，主动邀请对方一起玩。",
      pinyin: "Duì xīn tóngxué, tā yǔrén-wéishàn, zhǔdòng yāoqǐng duìfāng yìqǐ wán.",
      english: "Toward the new classmate, he was warm and kind — he went out of his way to invite them to play together.",
      charPinyin: ["duì", "xīn", "tóng", "xué", "", "tā", "yǔ", "rén", "wéi", "shàn", "", "zhǔ", "dòng", "yāo", "qǐng", "duì", "fāng", "yì", "qǐ", "wán", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning/origin (《孟子·公孙丑上》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "le-shan-hao-shi",
    hanzi: "乐善好施",
    pinyin: "lè shàn hào shī",
    literalMeaning: "乐 (joyfully) 善 (good deeds) 好 (fond of) 施 (giving) — joyfully fond of doing good deeds and giving to others.",
    meaning: "Being genuinely happy to give and be generous to others, not just when asked.",
    meaningZh: {
      hanzi: "喜欢做好事，很愿意把自己的东西分给别人。",
      pinyin: "Xǐhuan zuò hǎoshì, hěn yuànyì bǎ zìjǐ de dōngxi fēn gěi biérén.",
      charPinyin: ["xǐ", "huan", "zuò", "hǎo", "shì", "", "hěn", "yuàn", "yì", "bǎ", "zì", "jǐ", "de", "dōng", "xi", "fēn", "gěi", "bié", "rén", ""],
    },
    dailyLifeScenario:
      "When your school collects toys and books for children who don't have many, you happily go through your own shelf and give away some of your favourites, without being asked twice. That eager generosity is 乐善好施.",
    exampleSentence: {
      hanzi: "学校募捐时，他乐善好施，捐出了好几本图书。",
      pinyin: "Xuéxiào mùjuān shí, tā lèshàn-hàoshī, juānchū le hǎo jǐ běn túshū.",
      english: "During the school donation drive, he was joyfully generous and donated several of his own books.",
      charPinyin: ["xué", "xiào", "mù", "juān", "shí", "", "tā", "lè", "shàn", "hào", "shī", "", "juān", "chū", "le", "hǎo", "jǐ", "běn", "tú", "shū", ""],
    },
    ageBand: "lower-primary",
    theme: "kindness",
    sourceNotes: "Meaning/origin (《史记·乐书二》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },

  // --- Wisdom & Learning ---
  {
    id: "wen-gu-zhi-xin",
    hanzi: "温故知新",
    pinyin: "wēn gù zhī xīn",
    literalMeaning: "温 (review) 故 (the old) 知 (understand) 新 (the new) — review the old, and thereby understand the new.",
    meaning: "Going back over what you've already learned helps you understand new things better.",
    meaningZh: {
      hanzi: "把以前学过的东西再复习一遍，可以帮助自己更好地理解新的知识。",
      pinyin: "Bǎ yǐqián xuéguò de dōngxi zài fùxí yí biàn, kěyǐ bāngzhù zìjǐ gèng hǎo de lǐjiě xīn de zhīshi.",
      charPinyin: ["bǎ", "yǐ", "qián", "xué", "guò", "de", "dōng", "xi", "zài", "fù", "xí", "yí", "biàn", "", "kě", "yǐ", "bāng", "zhù", "zì", "jǐ", "gèng", "hǎo", "de", "lǐ", "jiě", "xīn", "de", "zhī", "shi", ""],
    },
    dailyLifeScenario:
      "Before a spelling test, you flip back through last month's word lists to review them — this helps the new words make more sense too. That's 温故知新.",
    exampleSentence: {
      hanzi: "他每天温故知新，先复习旧的生字，读新课文时就觉得容易多了。",
      pinyin: "Tā měitiān wēngù-zhīxīn, xiān fùxí jiù de shēngzì, dú xīn kèwén shí jiù juéde róngyì duō le.",
      english: "He reviews old lessons every day — that's why new lessons feel much easier to read.",
      charPinyin: ["tā", "měi", "tiān", "wēn", "gù", "zhī", "xīn", "", "xiān", "fù", "xí", "jiù", "de", "shēng", "zì", "", "dú", "xīn", "kè", "wén", "shí", "jiù", "jué", "de", "róng", "yì", "duō", "le", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Origin: 论语·为政 (Confucius). Concrete, directly actionable study-habit idiom.",
  },
  {
    id: "shou-zhu-dai-tu",
    hanzi: "守株待兔",
    pinyin: "shǒu zhū dài tù",
    literalMeaning: "守 (guard) 株 (a tree stump) 待 (wait for) 兔 (a rabbit) — guarding a tree stump, waiting for a rabbit.",
    meaning: "Hoping good things will happen by luck alone, instead of working for them.",
    meaningZh: {
      hanzi: "什么都不努力去做，只是傻傻地等着好运气自己出现。",
      pinyin: "Shénme dōu bù nǔlì qù zuò, zhǐshì shǎshǎ de děng zhe hǎo yùnqi zìjǐ chūxiàn.",
      charPinyin: ["shén", "me", "dōu", "bù", "nǔ", "lì", "qù", "zuò", "", "zhǐ", "shì", "shǎ", "shǎ", "de", "děng", "zhe", "hǎo", "yùn", "qi", "zì", "jǐ", "chū", "xiàn", ""],
    },
    dailyLifeScenario:
      "You hope to do well in your spelling test just by 'getting lucky,' instead of studying the word list. A friend might remind you that you can't just 守株待兔.",
    exampleSentence: {
      hanzi: "他从来不认真复习，只是守株待兔，希望考试的时候能靠运气答对。",
      pinyin: "Tā cónglái bú rènzhēn fùxí, zhǐshì shǒuzhū-dàitù, xīwàng kǎoshì de shíhou néng kào yùnqi dáduì.",
      english: "He never studies seriously — he just sits around hoping for a stroke of luck, wishing he can get the answers right by chance when the exam comes.",
      charPinyin: ["tā", "cóng", "lái", "bú", "rèn", "zhēn", "fù", "xí", "", "zhǐ", "shì", "shǒu", "zhū", "dài", "tù", "", "xī", "wàng", "kǎo", "shì", "de", "shí", "hou", "néng", "kào", "yùn", "qi", "dá", "duì", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Origin: 韩非子·五蠹. Reportedly used in Singapore's 《欢乐伙伴》 textbook material.",
  },
  {
    id: "jing-di-zhi-wa",
    hanzi: "井底之蛙",
    pinyin: "jǐng dǐ zhī wā",
    literalMeaning: "井 (a well) 底 (the bottom) 之 (of) 蛙 (a frog) — a frog at the bottom of a well.",
    meaning: "Someone who thinks their small world is all there is, not realising how much bigger the world really is.",
    meaningZh: {
      hanzi: "以为自己知道的东西就是全部，不知道外面的世界其实更大更精彩。",
      pinyin: "Yǐwéi zìjǐ zhīdào de dōngxi jiùshì quánbù, bù zhīdào wàimiàn de shìjiè qíshí gèng dà gèng jīngcǎi.",
      charPinyin: ["yǐ", "wéi", "zì", "jǐ", "zhī", "dào", "de", "dōng", "xi", "jiù", "shì", "quán", "bù", "", "bù", "zhī", "dào", "wài", "miàn", "de", "shì", "jiè", "qí", "shí", "gèng", "dà", "gèng", "jīng", "cǎi", ""],
    },
    dailyLifeScenario:
      "You think you're the best drawer in your class — until you visit an art exhibition and see how many amazing styles of drawing exist. Realising there's always more to learn is the opposite of being a 井底之蛙.",
    exampleSentence: {
      hanzi: "参观了钟表制作展览后，他才发现自己以前就像井底之蛙，原来做一只手表要懂这么多学问。",
      pinyin: "Cānguān le zhōngbiǎo zhìzuò zhǎnlǎn hòu, tā cái fāxiàn zìjǐ yǐqián jiù xiàng jǐngdǐzhīwā, yuánlái zuò yì zhī shǒubiǎo yào dǒng zhème duō xuéwèn.",
      english: "After visiting a watchmaking exhibition, he realized he'd been like a frog in a well — it turns out making a single watch takes so much more knowledge than he ever imagined.",
      charPinyin: ["cān", "guān", "le", "zhōng", "biǎo", "zhì", "zuò", "zhǎn", "lǎn", "hòu", "", "tā", "cái", "fā", "xiàn", "zì", "jǐ", "yǐ", "qián", "jiù", "xiàng", "jǐng", "dǐ", "zhī", "wā", "", "yuán", "lái", "zuò", "yì", "zhī", "shǒu", "biǎo", "yào", "dǒng", "zhè", "me", "duō", "xué", "wèn", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Origin: 庄子·秋水. Lesson is slightly more abstract than other entries — included for thematic diversity.",
  },
  {
    id: "yi-ju-liang-de",
    hanzi: "一举两得",
    pinyin: "yī jǔ liǎng dé",
    literalMeaning: "一 (one) 举 (action, cf. 举手 'raise hand') 两 (two) 得 (gains) — one action, two gains.",
    meaning: "Doing one thing that gives you two benefits at once.",
    meaningZh: {
      hanzi: "只做一件事情，却同时得到了两种好处。",
      pinyin: "Zhǐ zuò yí jiàn shìqing, què tóngshí dédào le liǎng zhǒng hǎochù.",
      charPinyin: ["zhǐ", "zuò", "yí", "jiàn", "shì", "qing", "", "què", "tóng", "shí", "dé", "dào", "le", "liǎng", "zhǒng", "hǎo", "chù", ""],
    },
    dailyLifeScenario:
      "You walk to school with your dad instead of taking the car — you get to school and also get exercise and chat with him along the way. That's 一举两得.",
    exampleSentence: {
      hanzi: "走路去上学既能运动又能省钱，真是一举两得。",
      pinyin: "Zǒulù qù shàngxué jì néng yùndòng yòu néng shěngqián, zhēnshi yìjǔ-liǎngdé.",
      english: "Walking to school lets you exercise and save money — two gains from one action.",
      charPinyin: ["zǒu", "lù", "qù", "shàng", "xué", "jì", "néng", "yùn", "dòng", "yòu", "néng", "shěng", "qián", "", "zhēn", "shi", "yì", "jǔ", "liǎng", "dé", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes:
      "Origin: 战国策·秦策二. Classified at a fairly advanced level for L2 adult learners, but character difficulty is low for native-speaking children (一/两 taught early; 举 familiar from 举手 in class).",
  },
  {
    id: "ju-yi-fan-san",
    hanzi: "举一反三",
    pinyin: "jǔ yī fǎn sān",
    literalMeaning: "举 (raise/cite) 一 (one example) 反 (in turn infer) 三 (three others) — from one example raised, inferring three more.",
    meaning: "Learning one thing well enough that you can figure out other similar things on your own, without being taught each one separately.",
    meaningZh: {
      hanzi: "学会了一个方法，就能推想出很多类似的道理。",
      pinyin: "Xuéhuì le yí ge fāngfǎ, jiù néng tuīxiǎng chū hěn duō lèisì de dàolǐ.",
      charPinyin: ["xué", "huì", "le", "yí", "ge", "fāng", "fǎ", "", "jiù", "néng", "tuī", "xiǎng", "chū", "hěn", "duō", "lèi", "sì", "de", "dào", "lǐ", ""],
    },
    dailyLifeScenario:
      "After learning how to fold a paper crane, you realise you can figure out how to fold a paper boat or a paper airplane too, using the same folding techniques, without being taught each one separately. That's 举一反三.",
    exampleSentence: {
      hanzi: "他学会了怎么折纸鹤，举一反三，很快就学会了折纸船和纸飞机。",
      pinyin: "Tā xuéhuì le zěnme zhé zhǐhè, jǔyī-fǎnsān, hěn kuài jiù xuéhuì le zhé zhǐchuán hé zhǐfēijī.",
      english: "After learning how to fold a paper crane, he applied the same idea and quickly figured out how to fold a paper boat and a paper airplane too.",
      charPinyin: ["tā", "xué", "huì", "le", "zěn", "me", "zhé", "zhǐ", "hè", "", "jǔ", "yī", "fǎn", "sān", "", "hěn", "kuài", "jiù", "xué", "huì", "le", "zhé", "zhǐ", "chuán", "hé", "zhǐ", "fēi", "jī", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (《论语·述而》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "wei-yu-chou-mou",
    hanzi: "未雨绸缪",
    pinyin: "wèi yǔ chóu móu",
    literalMeaning: "未 (before) 雨 (rain) 绸缪 (mend tightly, i.e. repair the roof) — mending the roof before it rains.",
    meaning: "Getting ready for something before it happens, instead of waiting until it's too late.",
    meaningZh: {
      hanzi: "在事情发生之前就先做好准备，不要等到事到临头才着急。",
      pinyin: "Zài shìqing fāshēng zhīqián jiù xiān zuò hǎo zhǔnbèi, bú yào děngdào shì dào líntóu cái zháojí.",
      charPinyin: ["zài", "shì", "qing", "fā", "shēng", "zhī", "qián", "jiù", "xiān", "zuò", "hǎo", "zhǔn", "bèi", "", "bú", "yào", "děng", "dào", "shì", "dào", "lín", "tóu", "cái", "zháo", "jí", ""],
    },
    dailyLifeScenario:
      "You know a spelling test is coming up in two weeks, so you start reviewing a little bit every day well ahead of time, instead of cramming the night before. That looking-ahead preparation is 未雨绸缪.",
    exampleSentence: {
      hanzi: "他每天多复习一点，未雨绸缪，考试来临时才不会手忙脚乱。",
      pinyin: "Tā měitiān duō fùxí yìdiǎn, wèiyǔ-chóumóu, kǎoshì láilín shí cái bú huì shǒumáng-jiǎoluàn.",
      english: "He reviews a little extra every day, preparing ahead of time, so when the exam comes he won't be flustered.",
      charPinyin: ["tā", "měi", "tiān", "duō", "fù", "xí", "yì", "diǎn", "", "wèi", "yǔ", "chóu", "móu", "", "kǎo", "shì", "lái", "lín", "shí", "cái", "bú", "huì", "shǒu", "máng", "jiǎo", "luàn", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (《诗经·豳风·鸱鸮》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "rong-hui-guan-tong",
    hanzi: "融会贯通",
    pinyin: "róng huì guàn tōng",
    literalMeaning: "融 (melt/blend) 会 (together) 贯 (thread through) 通 (fully understand) — blending knowledge together until it all threads through into full understanding.",
    meaning: "Connecting different pieces of knowledge together until you truly and fully understand the whole picture, not just separate facts.",
    meaningZh: {
      hanzi: "把学过的各种知识连接起来，变成一个完整清楚的理解。",
      pinyin: "Bǎ xuéguò de gèzhǒng zhīshi liánjiē qǐlái, biànchéng yí ge wánzhěng qīngchu de lǐjiě.",
      charPinyin: ["bǎ", "xué", "guò", "de", "gè", "zhǒng", "zhī", "shi", "lián", "jiē", "qǐ", "lái", "", "biàn", "chéng", "yí", "ge", "wán", "zhěng", "qīng", "chu", "de", "lǐ", "jiě", ""],
    },
    dailyLifeScenario:
      "You've practised pedaling and practised keeping your balance separately — then one day it all clicks, and you can finally ride a bike. That connecting-the-dots, putting-it-all-together understanding is 融会贯通.",
    exampleSentence: {
      hanzi: "他先学会踩踏板和保持平衡，最后融会贯通，终于学会骑自行车了。",
      pinyin: "Tā xiān xuéhuì cǎi tàbǎn hé bǎochí pínghéng, zuìhòu rónghuì-guàntōng, zhōngyú xuéhuì qí zìxíngchē le.",
      english: "He first learned to pedal and to keep his balance separately — finally putting it all together, he could finally ride a bike.",
      charPinyin: ["tā", "xiān", "xué", "huì", "cǎi", "tà", "bǎn", "hé", "bǎo", "chí", "píng", "héng", "", "zuì", "hòu", "róng", "huì", "guàn", "tōng", "", "zhōng", "yú", "xué", "huì", "qí", "zì", "xíng", "chē", "le", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (《朱子全书·学三》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "ji-si-guang-yi",
    hanzi: "集思广益",
    pinyin: "jí sī guǎng yì",
    literalMeaning: "集 (gather) 思 (thoughts) 广 (widen) 益 (benefit) — gathering everyone's ideas to widen the benefit for all.",
    meaning: "Bringing everyone's ideas together so the whole group ends up with a better solution than any one person could find alone.",
    meaningZh: {
      hanzi: "把大家的想法都收集起来，共同得到更好的办法。",
      pinyin: "Bǎ dàjiā de xiǎngfǎ dōu shōují qǐlái, gòngtóng dédào gèng hǎo de bànfǎ.",
      charPinyin: ["bǎ", "dà", "jiā", "de", "xiǎng", "fǎ", "dōu", "shōu", "jí", "qǐ", "lái", "", "gòng", "tóng", "dé", "dào", "gèng", "hǎo", "de", "bàn", "fǎ", ""],
    },
    dailyLifeScenario:
      "Your group needs to decide how to design your class poster. Instead of just doing it your own way, you ask everyone for ideas first and combine the best of all of them. That's 集思广益.",
    exampleSentence: {
      hanzi: "设计海报时，大家集思广益，想出了更好的点子。",
      pinyin: "Shèjì hǎibào shí, dàjiā jísī-guǎngyì, xiǎngchū le gèng hǎo de diǎnzi.",
      english: "While designing the poster, everyone pooled their ideas, and they came up with an even better one.",
      charPinyin: ["shè", "jì", "hǎi", "bào", "shí", "", "dà", "jiā", "jí", "sī", "guǎng", "yì", "", "xiǎng", "chū", "le", "gèng", "hǎo", "de", "diǎn", "zi", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (三国·蜀·诸葛亮《教与军师长史参军掾属》) confirmed via zdic.net and Baidu Baike (2026-09-09 search).",
  },
  {
    id: "ming-cha-qiu-hao",
    hanzi: "明察秋毫",
    pinyin: "míng chá qiū háo",
    literalMeaning: "明 (clearly) 察 (perceive) 秋 (autumn) 毫 (fine down) — perceiving clearly even the fine down an animal grows in autumn.",
    meaning: "Noticing even the tiniest details that most people would miss.",
    meaningZh: {
      hanzi: "观察事情非常仔细，连很小的细节都能发现。",
      pinyin: "Guānchá shìqing fēicháng zǐxì, lián hěn xiǎo de xìjié dōu néng fāxiàn.",
      charPinyin: ["guān", "chá", "shì", "qing", "fēi", "cháng", "zǐ", "xì", "", "lián", "hěn", "xiǎo", "de", "xì", "jié", "dōu", "néng", "fā", "xiàn", ""],
    },
    dailyLifeScenario:
      "While looking for your missing eraser, you notice a tiny mark on the floor that nobody else saw, and it leads you straight to where it rolled. Spotting details that small is 明察秋毫.",
    exampleSentence: {
      hanzi: "老师明察秋毫，一下子就看出作业是抄来的。",
      pinyin: "Lǎoshī míngchá-qiūháo, yíxiàzi jiù kàn chū zuòyè shì chāo lái de.",
      english: "The teacher notices even the smallest details — she spotted right away that the homework had been copied.",
      charPinyin: ["lǎo", "shī", "míng", "chá", "qiū", "háo", "", "yí", "xià", "zi", "jiù", "kàn", "chū", "zuò", "yè", "shì", "chāo", "lái", "de", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (《孟子·梁惠王上》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "xue-yi-zhi-yong",
    hanzi: "学以致用",
    pinyin: "xué yǐ zhì yòng",
    literalMeaning: "学 (study) 以 (in order to) 致 (bring about) 用 (application) — studying in order to put it to actual use.",
    meaning: "Actually using what you've learned in real life, not just memorizing it for a test.",
    meaningZh: {
      hanzi: "把学过的知识真正用在实际生活当中。",
      pinyin: "Bǎ xuéguò de zhīshi zhēnzhèng yòng zài shíjì shēnghuó dāngzhōng.",
      charPinyin: ["bǎ", "xué", "guò", "de", "zhī", "shi", "zhēn", "zhèng", "yòng", "zài", "shí", "jì", "shēng", "huó", "dāng", "zhōng", ""],
    },
    dailyLifeScenario:
      "After learning about fractions in class, you use them to split a pizza fairly between four friends at home. Actually putting what you learned to real use like that is 学以致用.",
    exampleSentence: {
      hanzi: "学了分数以后，他学以致用，公平地分好了披萨。",
      pinyin: "Xué le fēnshù yǐhòu, tā xuéyǐ-zhìyòng, gōngpíng de fēn hǎo le pīsà.",
      english: "After learning about fractions, he put what he learned to real use, dividing the pizza fairly.",
      charPinyin: ["xué", "le", "fēn", "shù", "yǐ", "hòu", "", "tā", "xué", "yǐ", "zhì", "yòng", "", "gōng", "píng", "de", "fēn", "hǎo", "le", "pī", "sà", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "yin-di-zhi-yi",
    hanzi: "因地制宜",
    pinyin: "yīn dì zhì yí",
    literalMeaning: "因 (according to) 地 (the place) 制 (decide) 宜 (what's suitable) — deciding what's suitable according to the actual place/situation.",
    meaning: "Adjusting your plan to fit the actual situation you're in, instead of using the same approach everywhere.",
    meaningZh: {
      hanzi: "根据实际的情况，想出最合适的办法。",
      pinyin: "Gēnjù shíjì de qíngkuàng, xiǎngchū zuì héshì de bànfǎ.",
      charPinyin: ["gēn", "jù", "shí", "jì", "de", "qíng", "kuàng", "", "xiǎng", "chū", "zuì", "hé", "shì", "de", "bàn", "fǎ", ""],
    },
    dailyLifeScenario:
      "Your class wants to grow a vegetable garden, but the sunny side of the yard is best for tomatoes while the shady side suits lettuce better — so you plant each vegetable where it actually grows best. That's 因地制宜.",
    exampleSentence: {
      hanzi: "种菜的时候，他们因地制宜，把不同的菜种在合适的地方。",
      pinyin: "Zhòng cài de shíhou, tāmen yīndì-zhìyí, bǎ bùtóng de cài zhòng zài héshì de dìfang.",
      english: "While planting vegetables, they adapted to the actual conditions, planting each vegetable where it suited best.",
      charPinyin: ["zhòng", "cài", "de", "shí", "hou", "", "tā", "men", "yīn", "dì", "zhì", "yí", "", "bǎ", "bù", "tóng", "de", "cài", "zhòng", "zài", "hé", "shì", "de", "dì", "fang", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (汉·赵晔《吴越春秋·阖闾内传》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
  {
    id: "shen-si-shu-lv",
    hanzi: "深思熟虑",
    pinyin: "shēn sī shú lǜ",
    literalMeaning: "深 (deeply) 思 (think) 熟 (thoroughly) 虑 (consider) — thinking deeply and considering thoroughly.",
    meaning: "Thinking carefully and thoroughly about something before deciding, instead of rushing into it.",
    meaningZh: {
      hanzi: "做决定之前认真仔细地想清楚，不急着做。",
      pinyin: "Zuò juédìng zhīqián rènzhēn zǐxì de xiǎng qīngchu, bù jízhe zuò.",
      charPinyin: ["zuò", "jué", "dìng", "zhī", "qián", "rèn", "zhēn", "zǐ", "xì", "de", "xiǎng", "qīng", "chu", "", "bù", "jí", "zhe", "zuò", ""],
    },
    dailyLifeScenario:
      "Before choosing which club to join, you think carefully about what you actually enjoy and how much time you have, instead of just picking whatever your friend picked. That careful thinking-it-through is 深思熟虑.",
    exampleSentence: {
      hanzi: "选兴趣班之前，他深思熟虑，考虑了很久才决定。",
      pinyin: "Xuǎn xìngqùbān zhīqián, tā shēnsī-shúlǜ, kǎolǜ le hěn jiǔ cái juédìng.",
      english: "Before choosing an enrichment class, he thought it through carefully, considering it for a long time before deciding.",
      charPinyin: ["xuǎn", "xìng", "qù", "bān", "zhī", "qián", "", "tā", "shēn", "sī", "shú", "lǜ", "", "kǎo", "lǜ", "le", "hěn", "jiǔ", "cái", "jué", "dìng", ""],
    },
    ageBand: "lower-primary",
    theme: "wisdom",
    sourceNotes: "Meaning/origin (《楚辞·渔父》/《史记·穰侯列传》) confirmed via zdic.net and Baidu Baike (2026-09-10 search).",
  },
];

export const idiomsById: Record<string, IdiomContent> = Object.fromEntries(
  idioms.map((idiom) => [idiom.id, idiom]),
);
